# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=dev
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Engine_config = debug
  Game_config = debug
  ToadRunner_config = debug

else ifeq ($(config),release)
  Engine_config = release
  Game_config = release
  ToadRunner_config = release

else ifeq ($(config),dev)
  Engine_config = dev
  Game_config = dev
  ToadRunner_config = dev

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Engine Game ToadRunner

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Engine:
ifneq (,$(Engine_config))
	@echo "==== Building Engine ($(Engine_config)) ===="
	@${MAKE}  -C Engine -f Makefile config=$(Engine_config)
endif

Game: Engine
ifneq (,$(Game_config))
	@echo "==== Building Game ($(Game_config)) ===="
	@${MAKE}  -C Game -f Makefile config=$(Game_config)
endif

ToadRunner: Engine Game
ifneq (,$(ToadRunner_config))
	@echo "==== Building ToadRunner ($(ToadRunner_config)) ===="
	@${MAKE}  -C ToadRunner -f Makefile config=$(ToadRunner_config)
endif

clean:
	@${MAKE}  -C Engine -f Makefile clean
	@${MAKE}  -C Game -f Makefile clean
	@${MAKE}  -C ToadRunner -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dev"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Engine"
	@echo "   Game"
	@echo "   ToadRunner"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"