name: build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/build.yml'
      - '!**.md'

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: Onion.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build-config: [Distro, Release, Debug]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with: 
        python-version: '3.13'
        
    - name: Setup
      working-directory: ${{env.GIHUB_WORKSPACE}}
      run: |
        cd scripts
        ./setup.bat

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ${{ env.SOLUTION_FILE_PATH }} /m /p:Configuration=${{ matrix.build-config }}
